# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edad57fe7441a3c1a413883f174dd8b8a83b962d861a13f6d45d7210e0986cb5a66d84dce7328b62a0c70d1bdf3c19db2788843e63b61ef20ddcef35f519a7a4

test:
  secret_key_base: b1423a823412dd03ec35908c2417ec2d2beb1682f4d7dc5f6240a666c1bb784596d660125ab2134826030615f71d01f4efdafc936befc5fe2ab577d8a8f47ca4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
